# Author: Yifan Fan (yifan.fan@dian.fm)

cc_library(
  name = 'default_poller',
  srcs = [ 'default_poller.cpp' ],
  deps = [
    ':poll_poller',
    ':epoll_poller',
  ]
)

cc_library(
  name = 'poll_poller',
  srcs = [ 'poll_poller.cpp' ],
  deps = [
  ]
)

cc_library(
  name = 'epoll_poller',
  srcs = [ 'epoll_poller.cpp' ],
  deps = [
  ]
)
