# Author: Yifan Fan (yifan.fan@dian.fm)

cc_library(
  name = 'libmuduo_cpp11-base',
  srcs = [
    'logging.cpp',
    'thread_pool.cpp',
    'timestamp.cpp',
  ],
  deps = [
    '#rt',
    '#glog',
    '#pthread'
  ]
)
