# Author: Yifan Fan (yifan.fan.1983@gmail.com)

cc_library(
  name = 'libmuduo_cpp11-net',
  srcs = [
    'acceptor.cpp',
    'buffer.cpp',
    'channel.cpp',
    'connector.cpp',
    'event_loop.cpp',
    'event_loop_thread.cpp',
    'event_loop_thread_pool.cpp',
    'http/http_response.cpp',
    'http/http_server.cpp',
    'inet_address.cpp',
    'poller.cpp',
    'poller/default_poller.cpp',
    'poller/epoll_poller.cpp',
    'poller/poll_poller.cpp',
    'socket.cpp',
    'sockets_ops.cpp',
    'tcp_client.cpp',
    'tcp_connection.cpp',
    'tcp_server.cpp',
    'timer.cpp',
    'timer_queue.cpp',
  ],
  deps = [
    '//muduo-cpp11/base:libmuduo_cpp11-base',
  ]
)
